$(document).ready(function(){
    $(".blog1").show()
    $(".blog2").hide()
    $(".blog3").hide()
    $(".blog4").hide()
    $(".blog5").hide()
    $(".blog1click").click(function(){
        $(".blog1").show()
        $(".blog2").hide()
        $(".blog3").hide()
        $(".blog4").hide()
        $(".blog5").hide()
    });
    $(".blog2click").click(function(){
        $(".blog1").hide()
        $(".blog2").show()
        $(".blog3").hide()
        $(".blog4").hide()
        $(".blog5").hide()
    });
    $(".blog3click").click(function(){
        $(".blog1").hide()
        $(".blog2").hide()
        $(".blog3").show()
        $(".blog4").hide()
        $(".blog5").hide()
    });
    $(".blog4click").click(function(){
        $(".blog1").hide()
        $(".blog2").hide()
        $(".blog3").hide()
        $(".blog4").show()
        $(".blog5").hide()
    });
    $(".blog5click").click(function(){
        $(".blog1").hide()
        $(".blog2").hide()
        $(".blog3").hide()
        $(".blog4").hide()
        $(".blog5").show()
    });
});